options:
  plugin:
    default: ovs
    type: string
    description: |
      Network configuration plugin to use for quantum.
      Supported values include:
      .
        ovs - OpenVSwitch
        nvp - Nicira NVP
        n1kv - Cisco N1kv
  ext-port:
    type: string
    description: |
      External port to use for routing of instance
      traffic to the external public network.
  openstack-origin:
    type: string
    default: distro
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-folsom/proposed
        - cloud:precise-folsom
        - deb http://my.archive.com/ubuntu main|KEYID
      .
      Note that quantum/neutron is only supported >= Folsom.
  run-internal-router:
    type: string
    default: all
    description: |
      Optional configuration to support how the L3 agent option
      handle_internal_only_routers is configured.
      all    => Set to be true everywhere
      none   => Set to be false everywhere
      leader => Set to be true on one node (the leader) and false everywhere
                else.
      Use leader and none when configuring multiple floating pools
  external-network-id:
    type: string
    description: |
      Optional configuration to set the external-network-id. Only needed when
      configuring multiple external networks and should be used in conjunction
      with run-internal-router.
  rabbit-user:
    type: string
    default: neutron
  rabbit-vhost:
    type: string
    default: openstack
  n1kv-source:
    type: string
    default: distro
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - deb http://my.archive.com/ubuntu main|KEYID
      .
      Note that this is used only for Cisco n1kv plugin.
  l3-agent:
    type: string
    default: enable 
    description: |
      Optional configuration to support use of linux router
      Note that this is used only for Cisco n1kv plugin.
